name: Triggered Workflow

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Name of the user"
        required: true
      email:
        description: "Email of the user"
        required: true
      subject:
        description: "Subject of the issue"
        required: true
      message:
        description: "Message from the user"
        required: true

jobs:
  create-issue:
    runs-on: ubuntu-22.04

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Create an issue
        run: |
          curl -X POST -H "Authorization: Bearer ${{ secrets.PAT_KEY }}" \
          -H "Accept: application/vnd.github+json" \
          https://api.github.com/repos/${{ github.repository }}/issues \
          -d '{
            "title": "${{ github.event.inputs.subject }}",
            "body": "Name: ${{ github.event.inputs.name }}\nEmail: ${{ github.event.inputs.email }}\n\n${{ github.event.inputs.message }}"
          }'
