name: Create Issue from Form Submission

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Submitter name'
        required: true
      email:
        description: 'Submitter email'
        required: true
      subject:
        description: 'Issue subject'
        required: true
      feedback:
        description: 'Feedback content'
        required: true

jobs:
  create_issue:
    runs-on: ubuntu-22.04

    steps:
    - name: Create Issue
      uses: actions/github-script@v6
      with:
        script: |
          const { name, email, subject, feedback } = github.context.payload.inputs;
          const response = await github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: subject,
            body: `**Name:** ${name}\n**Email:** ${email}\n\n**Feedback:**\n${feedback}`,
          });
          core.setOutput('issue', response.data.html_url);