name: Create Issue via API

on:
  workflow_dispatch:
    inputs:
      title:
        description: 'Issue Title'
        required: true
        type: string
      body:
        description: 'Issue Body'
        required: true
        type: string

jobs:
  create-issue:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create GitHub issue using user input
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.PAT_KEY }}" \
            -H "Content-Type: application/json" \
            -d '{"title": "${{ github.event.inputs.title }}", "body": "${{ github.event.inputs.body }}"}' \
            https://api.github.com/repos/${{ github.repository }}/issues
